version: '2.17'

services:
  simulator:
    image: ghcr.io/autowarefoundation/openadkit_demo.autoware:aws-reinvent-simulator-monolithic-amd64
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=99
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: >
      ros2 launch scenario_test_runner scenario_test_runner.launch.py
      architecture_type:=awf/universe/20240605
      record:=false
      scenario:=$(find-pkg-share scenario_test_runner)/scenario/sample.yaml
      sensor_model:=sample_sensor_kit
      vehicle_model:=sample_vehicle
      initialize_duration:=90
      global_frame_rate:=15
      launch_autoware:=false
      launch_rviz:=true

  planning-control:
    image: ghcr.io/autowarefoundation/autoware:universe-amd64
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=99
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: >
      ros2 launch autoware_launch planning_simulator.launch.xml
      map_path:=/opt/autoware/share/kashiwanoha_map
      vehicle_model:=sample_vehicle
      sensor_model:=sample_sensor_kit
      scenario_simulation:=true
      rviz:=false