version: '2.17'

services:
  simulator:
    image: ghcr.io/autowarefoundation/openadkit_demo.autoware:ces-simulator-aarch64
    volumes:
      - /dev/shm:/dev/shm
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=88
    command: ros2 launch scenario_test_runner scenario_test_runner.launch.py architecture_type:=awf/universe record:=false scenario:=/autoware/scenario-sim/yield_maneuver_demo.yaml sensor_model:=sample_sensor_kit vehicle_model:=sample_vehicle map_path:=/autoware/scenario-sim/map/
  
  planning-control:
    image: ghcr.io/autowarefoundation/openadkit_demo.autoware:ces-planning-before-aarch64
    volumes:
      - /dev/shm:/dev/shm
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=88
    command: ros2 launch autoware_launch planning_simulator.launch.xml map_path:=/autoware/scenario-sim/map/ vehicle_model:=sample_vehicle sensor_model:=sample_sensor_kit scenario_simulation:=true use_foa:=false perception/enable_traffic_light:=false