name: load-env

on:
  workflow_call:
    outputs:
      rosdistro:
        value: ${{ jobs.load-env.outputs.rosdistro }}

jobs:
  load-env:
    runs-on: ubuntu-22.04
    outputs:
      rosdistro: ${{ steps.set-env.outputs.rosdistro }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Load env
        run: |
          cat amd64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          if [ "$(uname -m)" = "aarch64" ]; then
            cat arm64.env | sed -e "s/^\s*//" -e "/^#/d" >> $GITHUB_ENV
          fi

      - name: Set env
        id: set-env
        run: |
          echo "rosdistro=${{ env.rosdistro }}" >> $GITHUB_OUTPUT